networks:
  tests:
    driver: bridge

services:
  local-testing:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - pennsievedb-repositories
    networks:
      - tests

  pennsievedb-repositories:
    image: pennsieve/pennsievedb-repositories:20250319124829-seed
    restart: always
    ports:
      - "5432:5432"
    networks:
      - tests
