services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - pennsievedb-repositories
    environment:
      - AWS_ACCESS_KEY_ID=TestAWSKey
      - AWS_SECRET_ACCESS_KEY=TestAWSSecret
      - POSTGRES_HOST=pennsievedb-repositories
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=postgres
      # This var needs to be set to 'host.docker.internal' if the Docker server is Desktop and not Engine.
      # On Jenkins it is Engine and so, not needed, but if you run the test container
      # locally you will probably need it. Run the 'test-ci-local' Make target instead of 'test-ci'
      # and it will be set for you. See: https://golang.testcontainers.org/system_requirements/ci/dind_patterns/
      - TESTCONTAINERS_HOST_OVERRIDE
    volumes:
      # one of the tests uses testcontainers-go to start
      # a container. For this to work inside of Docker we
      # need to set this. See: https://golang.testcontainers.org/system_requirements/ci/dind_patterns/
      - /var/run/docker.sock:/var/run/docker.sock

  pennsievedb-repositories:
    image: pennsieve/pennsievedb-collections:20250422101951-seed
    restart: always
#    command: [ "postgres", "-c", "log_statement=all" ]

