FROM pennsieve/go-cloudwrap:1.23-alpine

WORKDIR /app

ENV CGO_ENABLED=0

COPY go.mod go.sum ./
RUN ["go", "mod", "download"]

COPY cmd cmd
COPY internal internal

RUN ["go", "build", "-o", "./repositories-dbmigrate", "cmd/dbmigrate/main.go"]

CMD ["--service", "repo-service-dbmigrate", "exec", "/app/repositories-dbmigrate"]
